import { BreakpointObserver, Breakpoints } from '@angular/cdk/layout';
import { Component } from '@angular/core';
import { map } from 'rxjs';

@Component({
  selector: 'app-dashboard',
  templateUrl: './dashboard.component.html',
  styleUrl: './dashboard.component.scss'
})
export class DashboardComponent {
  cards = this.breakpointObserver.observe(Breakpoints.Handset).pipe(
    map(({ matches }) => {
      if (matches) {
        return [
          { title: 'Beach', cols: 1, rows: 1, image:"assets/destination1.jpg", message:"A beach is a landform alongside a body of water which consists of loose particles. The particles composing a beach are typically made from rock, such as sand, gravel, shingle, pebbles, etc., or biological sources, such as mollusc shells or coralline algae. Sediments settle in different densities and structures, depending on the local wave action and weather, creating different textures, colors and gradients or layers of material. Though some beaches form on inland freshwater locations such as lakes and rivers, most beaches are in coastal areas where wave or current action deposits and reworks sediments. Erosion and changing of beach geologies happens through natural processes, like wave action and extreme weather events. Where wind conditions are correct, beaches can be backed by coastal dunes which offer protection and regeneration for the beach. However, these natural forces have become more extreme due to climate change, permanently altering beaches at very rapid rates. Some estimates describe as much as 50 percent of the earth's sandy beaches disappearing by 2100 due to climate-change driven sea level rise."},
          { title: 'Forest', cols: 1, rows: 1, image:"assets/destination2.jpg", message:"A forest is an ecosystem characterized by a dense community of trees. Hundreds of definitions of forest are used throughout the world, incorporating factors such as tree density, tree height, land use, legal standing, and ecological function."},
          { title: 'Aurora', cols: 1, rows: 1, image:"assets/destination3.jpg", message:"An aurora also commonly known as the northern lights (aurora borealis) or southern lights (aurora australis), is a natural light display in Earth's sky, predominantly seen in high-latitude regions (around the Arctic and Antarctic). Auroras display dynamic patterns of brilliant lights that appear as curtains, rays, spirals, or dynamic flickers covering the entire sky. Auroras are the result of disturbances in the Earth's magnetosphere caused by the solar wind. Major disturbances result from enhancements in the speed of the solar wind from coronal holes and coronal mass ejections. These disturbances alter the trajectories of charged particles in the magnetospheric plasma. These particles, mainly electrons and protons, precipitate into the upper atmosphere (thermosphere/exosphere). The resulting ionization and excitation of atmospheric constituents emit light of varying colour and complexity. The form of the aurora, occurring within bands around both polar regions, is also dependent on the amount of acceleration imparted to the precipitating particles. Most auroras occur in a band known as the auroral zone, which is typically 3° to 6° (approximately 330–660 km) wide in latitude and between 10° and 20° from the geomagnetic poles at all local times (or longitudes), most clearly seen at night against a dark sky. A region that currently displays an aurora is called the auroral oval, a band displaced by the solar wind towards the night side of Earth. Auroras at the North Pole itself are rare due to it being on the Arctic Ocean, while auroras at the South Pole itself are very common and guaranteed to be visible.[9] Early evidence for a geomagnetic connection comes from the statistics of auroral observations. Elias Loomis (1860),[10] and later Hermann Fritz (1881)[11] and Sophus Tromholt (1881)[12] in more detail, established that the aurora appeared mainly in the auroral zone." },
          { title: 'Mountain', cols: 1, rows: 1, image:"assets/destination4.jpg", message:"A mountain is an elevated portion of the Earth's crust, generally with steep sides that show significant exposed bedrock. Although definitions vary, a mountain may differ from a plateau in having a limited summit area, and is usually higher than a hill, typically rising at least 300 metres (980 ft) above the surrounding land." },
        ];
      }

      return [
        { title: 'Beach', cols: 2, rows: 1, image:"assets/destination1.jpg", message:"A beach is a landform alongside a body of water which consists of loose particles. The particles composing a beach are typically made from rock, such as sand, gravel, shingle, pebbles, etc., or biological sources, such as mollusc shells or coralline algae. Sediments settle in different densities and structures, depending on the local wave action and weather, creating different textures, colors and gradients or layers of material. Though some beaches form on inland freshwater locations such as lakes and rivers, most beaches are in coastal areas where wave or current action deposits and reworks sediments. Erosion and changing of beach geologies happens through natural processes, like wave action and extreme weather events. Where wind conditions are correct, beaches can be backed by coastal dunes which offer protection and regeneration for the beach. However, these natural forces have become more extreme due to climate change, permanently altering beaches at very rapid rates. Some estimates describe as much as 50 percent of the earth's sandy beaches disappearing by 2100 due to climate-change driven sea level rise."},
        { title: 'Forest', cols: 1, rows: 1, image:"assets/destination2.jpg", message:"A forest is an ecosystem characterized by a dense community of trees. Hundreds of definitions of forest are used throughout the world, incorporating factors such as tree density, tree height, land use, legal standing, and ecological function."},
        { title: 'Aurora', cols: 1, rows: 2, image:"assets/destination3.jpg", message:"An aurora also commonly known as the northern lights (aurora borealis) or southern lights (aurora australis), is a natural light display in Earth's sky, predominantly seen in high-latitude regions (around the Arctic and Antarctic). Auroras display dynamic patterns of brilliant lights that appear as curtains, rays, spirals, or dynamic flickers covering the entire sky. Auroras are the result of disturbances in the Earth's magnetosphere caused by the solar wind. Major disturbances result from enhancements in the speed of the solar wind from coronal holes and coronal mass ejections. These disturbances alter the trajectories of charged particles in the magnetospheric plasma. These particles, mainly electrons and protons, precipitate into the upper atmosphere (thermosphere/exosphere). The resulting ionization and excitation of atmospheric constituents emit light of varying colour and complexity. The form of the aurora, occurring within bands around both polar regions, is also dependent on the amount of acceleration imparted to the precipitating particles.Most auroras occur in a band known as the auroral zone, which is typically 3° to 6° (approximately 330–660 km) wide in latitude and between 10° and 20° from the geomagnetic poles at all local times (or longitudes), most clearly seen at night against a dark sky. A region that currently displays an aurora is called the auroral oval, a band displaced by the solar wind towards the night side of Earth. Auroras at the North Pole itself are rare due to it being on the Arctic Ocean, while auroras at the South Pole itself are very common and guaranteed to be visible.[9] Early evidence for a geomagnetic connection comes from the statistics of auroral observations. Elias Loomis (1860),[10] and later Hermann Fritz (1881)[11] and Sophus Tromholt (1881)[12] in more detail, established that the aurora appeared mainly in the auroral zone." },
        { title: 'Mountain', cols: 1, rows: 1, image:"assets/destination4.jpg", message:"A mountain is an elevated portion of the Earth's crust, generally with steep sides that show significant exposed bedrock. Although definitions vary, a mountain may differ from a plateau in having a limited summit area, and is usually higher than a hill, typically rising at least 300 metres (980 ft) above the surrounding land." },
      ];
    })
  );

  constructor(private breakpointObserver: BreakpointObserver) {}

}
